package com.fbart.eshop.loveshopping.model;
// Generated 2017-5-30 11:13:09 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TbUserInf generated by hbm2java
 */
public class TbUserInf implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private int sex;
	private String mobile;
	private String email;
	private String addr;
	private Date birth;

	public TbUserInf() {
	}

	public TbUserInf(String username, String password, int sex) {
		this.username = username;
		this.password = password;
		this.sex = sex;
	}

	public TbUserInf(String username, String password, int sex, String mobile, String email, String addr, Date birth) {
		this.username = username;
		this.password = password;
		this.sex = sex;
		this.mobile = mobile;
		this.email = email;
		this.addr = addr;
		this.birth = birth;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getSex() {
		return this.sex;
	}

	public void setSex(int sex) {
		this.sex = sex;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddr() {
		return this.addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	public Date getBirth() {
		return this.birth;
	}

	public void setBirth(Date birth) {
		this.birth = birth;
	}

}
